@*
 * Copyright 2010-2017 Artima, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *@

@import controllers.Application.scaladocsPageUrl
@import controllers.Application.latestScalacticScaladoc

@userGuidePage("Using assertions") {
<div style="text-align: left">

<h1>Using assertions</h1>

<p>
ScalaTest makes three assertions available by default in any style trait. You can use:
</p>

<ul>
<li><code>assert</code> for general assertions;</li>
<li><code>assertResult</code> to differentiate expected from actual values;</li>
<li><code>assertThrows</code> to ensure a bit of code throws an expected exception.</li>
</ul>

<p>
To get moving quickly in ScalaTest, learn and use these three assertions. Later if you prefer
you can switch to the more expressive <a href="/user_guide/using_matchers">matchers DSL</a>.
</p>

<p>
ScalaTest's assertions are defined in trait <a href='@scaladocsPageUrl("org.scalatest.Assertions")'><code>Assertions</code></a>, which is
extended by <a href='@scaladocsPageUrl("org.scalatest.Suite")'><code>Suite</code></a>, the supertrait to
all style traits. Trait <code>Assertions</code> also provides:
</p>

<ul>
<li><code>assume</code> to conditionally <em>cancel</em> a test;</li>
<li><code>fail</code> to fail a test unconditionally;</li>
<li><code>cancel</code> to cancel a test unconditionally;</li>
<li><code>succeed</code> to make a test succeed unconditionally;</li>
<li><code>intercept</code> to ensure a bit of code throws an expected exception and then make assertions about the exception;</li>
<li><code>assertDoesNotCompile</code> to ensure a bit of code does not compile;</li>
<li><code>assertCompiles</code> to ensure a bit of code does compile;</li>
<li><code>assertTypeError</code> to ensure a bit of code does not compile because of a type (not parse) error;</li>
<li><code>withClue</code> to add more information about a failure.</li>
</ul>

<p>
All of these constructs are described below.
</p>

<h4>The <code>assert</code> macro</h4>

<p>In any Scala program, you can write assertions by invoking <code>assert</code> and passing in a <code>Boolean</code> expression,
such as:</p><p><pre class="stHighlighted">
<span class="stReserved">val</span> left = <span class="stLiteral">2</span>
<span class="stReserved">val</span> right = <span class="stLiteral">1</span>
assert(left == right)
</pre></p><p>If the passed expression is <code>true</code>, <code>assert</code> will return normally. If <code>false</code>,
Scala's <code>assert</code> will complete abruptly with an <code>AssertionError</code>. This behavior is provided by
the <code>assert</code> method defined in object <code>Predef</code>, whose members are implicitly imported into every
Scala source file. This <code>Assertions</code> trait defines another <code>assert</code> method that hides the
one in <code>Predef</code>. It behaves the same, except that if <code>false</code> is passed it throws
<a href='@scaladocsPageUrl("org.scalatest.exceptions.TestFailedException")'><code>TestFailedException</code></a> instead of <code>AssertionError</code>.
Why? Because unlike <code>AssertionError</code>, <code>TestFailedException</code> carries information about exactly
which item in the stack trace represents
the line of test code that failed, which can help users more quickly find an offending line of code in a failing test.
In addition, ScalaTest's <code>assert</code> provides better error messages than Scala's <code>assert</code>.</p><p>If you pass the previous <code>Boolean</code> expression, <code>left == right</code> to <code>assert</code> in a ScalaTest test,
a failure will be reported that, because <code>assert</code> is implemented as a macro,
includes reporting the left and right values.
For example, given the same code as above but using ScalaTest assertions:</p><p><pre class="stHighlighted">
<span class="stReserved">import</span> org.scalatest.Assertions._
<span class="stReserved">val</span> left = <span class="stLiteral">2</span>
<span class="stReserved">val</span> right = <span class="stLiteral">1</span>
assert(left == right)
</pre></p><p>The detail message in the thrown <code>TestFailedException</code> from this <code>assert</code>
will be: &quot;2 did not equal 1&quot;.</p><p>ScalaTest's <code>assert</code> macro works by recognizing patterns in the AST of the expression passed to <code>assert</code> and,
for a finite set of common expressions, giving an error message that an equivalent ScalaTest matcher
expression would give. Here are some examples, where <code>a</code> is 1, <code>b</code> is 2, <code>c</code> is 3, <code>d</code>
is 4, <code>xs</code> is <code>List(a, b, c)</code>, and <code>num</code> is 1.0:</p><p><pre class="stHighlighted">
assert(a == b || c &gt;= d)
<span class="stLineComment">// Error message: 1 did not equal 2, and 3 was not greater than or equal to 4</span>

assert(xs.exists(_ == <span class="stLiteral">4</span>))
<span class="stLineComment">// Error message: List(1, 2, 3) did not contain 4</span>

assert(<span class="stQuotedString">"hello"</span>.startsWith(<span class="stQuotedString">"h"</span>) &amp;&amp; <span class="stQuotedString">"goodbye"</span>.endsWith(<span class="stQuotedString">"y"</span>))
<span class="stLineComment">// Error message: "hello" started with "h", but "goodbye" did not end with "y"</span>

assert(num.isInstanceOf[<span class="stType">Int</span>])
<span class="stLineComment">// Error message: 1.0 was not instance of scala.Int</span>

assert(<span class="stType">Some</span>(<span class="stLiteral">2</span>).isEmpty)
<span class="stLineComment">// Error message: Some(2) was not empty</span>
</pre></p><p>For expressions that are not recognized, the macro currently prints out a string
representation of the (desugared) AST and adds <code>"was false"</code>. Here are some examples of
error messages for unrecognized expressions:</p><p><pre class="stHighlighted">
assert(None.isDefined)
<span class="stLineComment">// Error message: scala.None.isDefined was false</span>

assert(xs.exists(i =&gt; i &gt; <span class="stLiteral">10</span>))
<span class="stLineComment">// Error message: xs.exists(((i: Int) =&gt; i.&gt;(10))) was false</span>
</pre></p><p>You can augment the standard error message by providing a <code>String</code> as a second argument
to <code>assert</code>, like this:</p><p><pre class="stHighlighted">
<span class="stReserved">val</span> attempted = <span class="stLiteral">2</span>
assert(attempted == <span class="stLiteral">1</span>, <span class="stQuotedString">"Execution was attempted "</span> + left + <span class="stQuotedString">" times instead of 1 time"</span>)
</pre></p><p>Using this form of <code>assert</code>, the failure report will be more specific to your problem domain, thereby
helping you debug the problem. This <code>Assertions</code> trait also mixes in the
<a href="@latestScalacticScaladoc/#org.scalactic.TripleEquals"><code>TripleEquals</code></a>, which gives you a <code>===</code> operator
that allows you to customize <a href="@latestScalacticScaladoc/#org.scalactic.Equality"><code>Equality</code></a>, perform equality checks with numeric
<a href="@latestScalacticScaladoc/#org.scalactic.Tolerance"><code>Tolerance</code></a>, and enforce type constraints at compile time with
sibling trait <a href="@latestScalacticScaladoc/#org.scalactic.TypeCheckedTripleEquals"><code>TypeCheckedTripleEquals</code></a>.</p><p><a name="expectedResults"></a></p><h4> Expected results </h4><p>Although the <code>assert</code> macro provides a natural, readable extension to Scala's <code>assert</code> mechanism that
provides good error messages, as the operands become lengthy, the code becomes less readable. In addition, the error messages
generated for <code>==</code> and <code>===</code> comparisons
don't distinguish between actual and expected values. The operands are just called <code>left</code> and <code>right</code>,
because if one were named <code>expected</code> and the other <code>actual</code>, it would be difficult for people to
remember which was which. To help with these limitations of assertions, <code>Suite</code> includes a method called <code>assertResult</code> that
can be used as an alternative to <code>assert</code>. To use <code>assertResult</code>, you place
the expected value in parentheses after <code>assertResult</code>, followed by curly braces containing code
that should result in the expected value. For example:</p><p><pre class="stHighlighted">
<span class="stReserved">val</span> a = <span class="stLiteral">5</span>
<span class="stReserved">val</span> b = <span class="stLiteral">2</span>
assertResult(<span class="stLiteral">2</span>) {
  a - b
}
</pre></p><p>In this case, the expected value is <code>2</code>, and the code being tested is <code>a - b</code>. This assertion will fail, and
the detail message in the <code>TestFailedException</code> will read, &quot;Expected 2, but got 3.&quot;</p><p><a name="forcingFailures"></a></p><h4> Forcing failures </h4><p>If you just need the test to fail, you can write:</p><p><pre class="stHighlighted">
fail()
</pre></p><p>Or, if you want the test to fail with a message, write:</p><p><pre class="stHighlighted">
fail(<span class="stQuotedString">"I've got a bad feeling about this"</span>)
</pre></p><p><a name="achievingSuccess"></a></p><h4> Achieving success </h4><p>In async style tests, you must end your test body with either <code>Future[Assertion]</code> or
<code>Assertion</code>. ScalaTest's assertions (including matcher expressions) have result type
<code>Assertion</code>, so ending with an assertion will satisfy the compiler.
If a test body or function body passed to <code>Future.map</code> does
<em>not</em> end with type <code>Assertion</code>, however, you can fix the type error by placing
<code>succeed</code> at the end of the
test or function body:</p><p><pre class="stHighlighted">
succeed <span class="stLineComment">// Has type Assertion</span>
</pre></p><p><a name="interceptedExceptions"></a>
<a name="expectedExceptions"></a></p><h4> Expected exceptions </h4><p>Sometimes you need to test whether a method throws an expected exception under certain circumstances, such
as when invalid arguments are passed to the method. You can do this in the JUnit 3 style, like this:</p><p><pre class="stHighlighted">
<span class="stReserved">val</span> s = <span class="stQuotedString">"hi"</span>
<span class="stReserved">try</span> {
  s.charAt(-<span class="stLiteral">1</span>)
  fail()
}
<span class="stReserved">catch</span> {
  <span class="stReserved">case</span> _: <span class="stType">IndexOutOfBoundsException</span> =&gt; <span class="stLineComment">// Expected, so continue</span>
}
</pre></p><p>If <code>charAt</code> throws <code>IndexOutOfBoundsException</code> as expected, control will transfer
to the catch case, which does nothing. If, however, <code>charAt</code> fails to throw an exception,
the next statement, <code>fail()</code>, will be run. The <code>fail</code> method always completes abruptly with
a <code>TestFailedException</code>, thereby signaling a failed test.</p><p>To make this common use case easier to express and read, ScalaTest provides two methods:
<code>assertThrows</code> and <code>intercept</code>.
Here's how you use <code>assertThrows</code>:</p><p><a name="assertThrowsMethod"></a>
<pre class="stHighlighted">
<span class="stReserved">val</span> s = <span class="stQuotedString">"hi"</span>
assertThrows[<span class="stType">IndexOutOfBoundsException</span>] { <span class="stLineComment">// Result type: Assertion</span>
  s.charAt(-<span class="stLiteral">1</span>)
}
</pre></p><p>This code behaves much like the previous example. If <code>charAt</code> throws an instance of <code>IndexOutOfBoundsException</code>,
<code>assertThrows</code> will return <code>Succeeded</code>. But if <code>charAt</code> completes normally, or throws a different
exception, <code>assertThrows</code> will complete abruptly with a <code>TestFailedException</code>.</p><p>The <code>intercept</code> method behaves the same as <code>assertThrows</code>, except that instead of returning <code>Succeeded</code>,
<code>intercept</code> returns the caught exception so that you can inspect it further if you wish. For example, you may need
to ensure that data contained inside the exception have expected values. Here's an example:</p><p><a name="interceptMethod"></a>
<pre class="stHighlighted">
<span class="stReserved">val</span> s = <span class="stQuotedString">"hi"</span>
<span class="stReserved">val</span> caught =
  intercept[<span class="stType">IndexOutOfBoundsException</span>] { <span class="stLineComment">// Result type: IndexOutOfBoundsException</span>
    s.charAt(-<span class="stLiteral">1</span>)
  }
assert(caught.getMessage.indexOf(<span class="stQuotedString">"-1"</span>) != -<span class="stLiteral">1</span>)
</pre></p><p><a name="checkingThatCodeDoesNotCompile"></a></p><h4> Checking that a snippet of code does or does not compile </h4><p>Often when creating libraries you may wish to ensure that certain arrangements of code that
represent potential &ldquo;user errors&rdquo; do not compile, so that your library is more error resistant.
ScalaTest's <code>Assertions</code> trait includes the following syntax for that purpose:</p><p><pre class="stHighlighted">
assertDoesNotCompile(<span class="stQuotedString">"val a: String = 1"</span>)
</pre></p><p>If you want to ensure that a snippet of code does not compile because of a type error (as opposed
to a syntax error), use:</p><p><pre class="stHighlighted">
assertTypeError(<span class="stQuotedString">"val a: String = 1"</span>)
</pre></p><p>Note that the <code>assertTypeError</code> call will only succeed if the given snippet of code does not
compile because of a type error. A syntax error will still result on a thrown <code>TestFailedException</code>.</p><p>If you want to state that a snippet of code <em>does</em> compile, you can make that
more obvious with:</p><p><pre class="stHighlighted">
assertCompiles(<span class="stQuotedString">"val a: Int = 1"</span>)
</pre></p><p>Although the previous three constructs are implemented with macros that determine at compile time whether
the snippet of code represented by the string does or does not compile, errors
are reported as test failures at runtime.</p><p><a name="assumptions"></a></p><h4> Assumptions </h4><p>Trait <code>Assertions</code> also provides methods that allow you to <em>cancel</em> a test.
You would cancel a test if a resource required by the test was unavailable. For example, if a test
requires an external database to be online, and it isn't, the test could be canceled to indicate
it was unable to run because of the missing database. Such a test <em>assumes</em> a database is
available, and you can use the <code>assume</code> method to indicate this at the beginning of
the test, like this:</p><p><pre class="stHighlighted">
assume(database.isAvailable)
</pre></p><p>For each overloaded <code>assert</code> method, trait <code>Assertions</code> provides an
overloaded <code>assume</code> method with an identical signature and behavior, except the
<code>assume</code> methods throw <a href='@scaladocsPageUrl("org.scalatest.exceptions.TestCanceledException")'><code>TestCanceledException</code></a> whereas the
<code>assert</code> methods throw <code>TestFailedException</code>. As with <code>assert</code>,
<code>assume</code> hides a Scala method in <code>Predef</code> that performs a similar
function, but throws <code>AssertionError</code>. And just as you can with <code>assert</code>,
you will get an error message extracted by a macro from the AST passed to <code>assume</code>, and can
optionally provide a clue string to augment this error message. Here are some examples:</p><p><pre class="stHighlighted">
assume(database.isAvailable, <span class="stQuotedString">"The database was down again"</span>)
assume(database.getAllUsers.count === <span class="stLiteral">9</span>)
</pre></p><p><a name="forcingCancelations"></a></p><h4> Forcing cancelations </h4><p>For each overloaded <code>fail</code> method, there's a corresponding <code>cancel</code> method
with an identical signature and behavior, except the <code>cancel</code> methods throw
<code>TestCanceledException</code> whereas the <code>fail</code> methods throw
<code>TestFailedException</code>. Thus if you just need to cancel a test, you can write:</p><p><pre class="stHighlighted">
cancel()
</pre></p><p>If you want to cancel the test with a message, just place the message in the parentheses:</p><p><pre class="stHighlighted">
cancel(<span class="stQuotedString">"Can't run the test because no internet connection was found"</span>)
</pre></p><p><a name="gettingAClue"></a></p><h4> Getting a clue </h4><p>If you want more information that is provided by default by the methods if this trait,
you can supply a &quot;clue&quot; string in one of several ways.
The extra information (or &quot;clues&quot;) you provide will
be included in the detail message of the thrown exception. Both
<code>assert</code> and <code>assertResult</code> provide a way for a clue to be
included directly, <code>intercept</code> does not.
Here's an example of clues provided directly in <code>assert</code>:</p><p><pre class="stHighlighted">
assert(<span class="stLiteral">1</span> + <span class="stLiteral">1</span> === <span class="stLiteral">3</span>, <span class="stQuotedString">"this is a clue"</span>)
</pre></p><p>and in <code>assertResult</code>:</p><p><pre class="stHighlighted">
assertResult(<span class="stLiteral">3</span>, <span class="stQuotedString">"this is a clue"</span>) { <span class="stLiteral">1</span> + <span class="stLiteral">1</span> }
</pre></p><p>The exceptions thrown by the previous two statements will include the clue
string, <code>"this is a clue"</code>, in the exception's detail message.
To get the same clue in the detail message of an exception thrown
by a failed <code>assertThrows</code> call requires using <code>withClue</code>:</p><p><pre class="stHighlighted">
withClue(<span class="stQuotedString">"this is a clue"</span>) {
  assertThrows[<span class="stType">IndexOutOfBoundsException</span>] {
    <span class="stQuotedString">"hi"</span>.charAt(-<span class="stLiteral">1</span>)
  }
}
</pre></p><p>The <code>withClue</code> method will only prepend the clue string to the detail
message of exception types that mix in the <code>ModifiableMessage</code> trait.
See the documentation for <a href='@scaladocsPageUrl("org.scalatest.exceptions.ModifiableMessage")'><code>ModifiableMessage</code></a> for more information.
If you wish to place a clue string after a block of code, see the documentation for
<a href='@scaladocsPageUrl("org.scalatest.AppendedClues")'><code>AppendedClues</code></a>.</p>

<p>
Next, learn about <a href="tagging_your_tests">tagging your tests</a>.
</p>

</div>
}
